### ISSUE TITLE
Update never finishes

### ISSUE THREAD

**Issue by dessant** [idleberg/atom-language-nsis#1]
The update button will keep animating, and the update will never end, there are no visible errors. Everything is ok after Atom is restarted.

Seen on Windows 10 with Atom 1.6.2, while updating from language-nsis 3.7.2 to 3.7.3.

**Comment by idleberg** [comment]
I've experienced this with several packages, but it seems more like a visual glitch. Usually switching views or reloading the window fixes this. Probably a bug in Atom.

**Comment by idleberg** [comment]
See [#532](https://github.com/atom/settings-view/issues/532) of **atom/settings-view**
