### ISSUE TITLE
console-panel now seems to be a requirement

### ISSUE THREAD

**Issue by nemchik** [idleberg/atom-language-nsis#2]
I noticed `console-panel` installed itself into my editor and when I removed it and restarted Atom it prompted me that `language-nsis` depends on `console-panel`. Can this dependency be removed?

**Comment by idleberg** [comment]
Just out of interest, what is your problem with dependencies. As a service provider, `console-panel` provides a reusable interface element, sparing me the need to come up with my own. I think of it as a convenience to provide better build logs.

Also, if you don't like the package, you can always just disable it. In commit 18a08279ed861d6474f3c12c1f55fefb554d5a6d, there is now a graceful fallback when `console-panel` is not available. Yet, I'm not fully convinced why I would also remove the dependency.

Looking forward to hear your thoughts!

**Comment by nemchik** [comment]
I simply don't use the `console-panel` package, even with `language-nsis`. I use `language-nsis` for syntax highlighting. My needs for the package are pretty basic. I use Atom on both my personal PC (that has decent power and speed) and a work PC (that's very sluggish). On my work PC I try to keep Atom as light as possible so that it runs smoothly. I also am fairly minimal when it comes to how I prefer my user interface. So I have no need visually or functionally for the `console-panel` package since the functionality it provides just isn't how I prefer to do things. And in the end isn't Atom all about preference?

As for why I don't just disable the package, that just brings me back to the question of why it was required in the first place? If it's not actually required to be enabled, and `language-nsis` functions while the package is disabled, then why bother making it a dependency? Also as petty as this may seem, having an additional package installed does take up disk space (barely important, but still valid).

For those who would like to use `console-panel` I'm sure they will seek it out and install it, but for those like myself who just want syntax highlighting it's rather intrusive to randomly have a language package force some random package on us.

**Comment by idleberg** [comment]
Thanks for the insights. In `v5.14.0` you can now to opt-out of automatic dependency installation in the package settings. I decided for opt-out (rather than opt-in), since I think that most people would want to see build logs.

![screen shot 2016-12-23 at 08 55 19](https://cloud.githubusercontent.com/assets/1504938/21449435/9389f06c-c8ed-11e6-8533-66c11012f967.png)

Once unchecked, you can uninstall dependencies.

**Comment by nemchik** [comment]
Thanks, I can confirm now that I am running 5.14.0 that the option added via https://github.com/idleberg/atom-language-nsis/commit/7caab90c3b535f9581de1e7eac0508bfd0de3db3 does allow me to remove the `console-panel` package.
