### ISSUE TITLE
Turn off auto-building?

### ISSUE THREAD

**Issue by asmaloney** [idleberg/atom-language-nsis#6]
How do I turn of the auto-building?

I want to use the plugin for syntax highlighting, but not building.

No matter what I do every time I save a .nsi file it pops up with an error.

Thanks!

**Comment by idleberg** [comment]
This package provides no auto-building. How do you save the file?

**Comment by asmaloney** [comment]
Well whatever it is that's looking for makensis every time I save the file then :-)

I'm just saving it like a normal file - control-S.

**Comment by idleberg** [comment]
The default shortcut for the build *Save & Compile*  command is <kbd>Shift</kbd>-<kbd>Alt</kbd>-<kbd>M</kbd>, so you probably have changed this – knowingly or not.

Open Atom's keybinding resolver (should be <kbd>Ctrl</kbd>+<kbd>.</kbd>) and then save the file as you normally do. In the bottom of your Atom window you should then see a dialog similar to this one:

![screenshot 2018-11-01 at 21 54 35 copy](https://user-images.githubusercontent.com/1504938/47879579-3dfbcf80-de21-11e8-8338-a0ec7d959479.png)

The default save command is `core:save`, while this packages provides the `NSIS:save-&-compile` command.

**Comment by asmaloney** [comment]
That's what I see.

I have not changed any key bindings, and the package settings show "alt-shift-M" as `NSIS:save-&-compile`.

But whenever I save I get the error:

`'makensis' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`

**Comment by asmaloney** [comment]
Oh - I see `core:win32.cson` since I'm running on Windows...

Is it possible something else is interfering? I don't have that many packages installed.

**Comment by idleberg** [comment]
> But whenever I save I get the error:
>
> `'makensis' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`

That's a very useful hint. You have installed the optional linter, but since it cannot find `makensis`, you get the error. To fix this, you should either add the NSIS installation directory to you `PATH` or add the path to `makensis.exe` in the settings of the linter package. If you don't want errors/warning shown in your scripts, you can instead delete or disable the `linter-makensis` package.

**Comment by asmaloney** [comment]
Aha! That's it.

I forgot about that other package and assumed errors with "makensis" were coming from this one.

Thanks Jan!
